//AUTOGENERATED FILE FROM png2asset
// Conversion args: bg_tiles.png -map -bpp 2 -c tileset.c -noflip

#ifndef METASPRITE_tileset_H
#define METASPRITE_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tileset_TILE_ORIGIN 0
#define tileset_TILE_W 8
#define tileset_TILE_H 8
#define tileset_WIDTH 40
#define tileset_HEIGHT 8
#define tileset_TILE_COUNT 5
#define tileset_PALETTE_COUNT 5
#define tileset_COLORS_PER_PALETTE 4
#define tileset_TOTAL_COLORS 20
#define tileset_MAP_ATTRIBUTES 0
extern const unsigned char tileset_map[5];
#define tileset_map_attributes tileset_map

BANKREF_EXTERN(tileset)

extern const palette_color_t tileset_palettes[20];
extern const uint8_t tileset_tiles[80];

#endif
